---
title: "Color and Stereo Vision Screening Protocol"
author: "Yiming Qian, Andrea Seisler, & Rick Gilmore"
date: "`r Sys.time()`"
output:
  html_document:
    keep_md: true
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

<!-- # Vision Screening Instructions -->

#### Color Test

##### Procedure

- The examination should be done indoors with bright, natural illumination of more than 300 lux ([lux](https://en.wikipedia.org/wiki/Lux) is a unit of illuminance. 320-500 lux is equivalent to office lighting.
- The plates should be held at a distance of 50 - 75 cm (20-30 inches)

Say:

>"This test assesses your color vision. Look at this picture and tell me what you see." 
>"Now trace the curve."

- The first exam:
    - *Skip: Examiner shows the participant plate 1 or 2, tracing the red line. Recognized as "circle", "square", or some other design.
    - Plate 3 and 4. The participants are required to say outloud "circle", "square", or some other design. If the shape is correctly recognized, mark as normal.If the shape is not correctly recognized, mark as abnormal.
- The second exam:
    - Skip: Examiner shows the participant plate 5. Recognized as a curve line. 
    - Plate 6: In tracing the winding line between the upper left mark x and lower right mark x, the normal traces the red curve, but the abnormal usually trace the blue.
    - Plate 7: In tracing the winding line between the upper left mark x and lower right mark x, the normal traces the upper green curve, but the abnormal usually trace the lower red curve.
    - Plate 8: In tracing the winding line between the upper left mark x, the normal can trace upper and lower curve and come back to the starting mark. In case of abnormal color vision, some can trace either contour.

When the participant is finished, say:

>"Great. Thank you." 

##### Report results

- Log the answer to each item on the score [score sheet](vision-screening-score-sheet.html).
- Those who can not recognize any curve in plate 8 at all, or any lower curve are definitely abnormal.
- They might be abnormal if they misjudge more than 3 plates among plates 3,4,6,7
- If they misjudge 1-2 plates among plates 3,4,6,7, it is better to re-examine him in details from plate 1-8. 
- Report the result into Qualtrics

#### Stereo Vision Test

##### Procedure

- Have the participant put the stereo glasses on.
- Have the participant sit at the desk and hold the book at arms length approximately perpindicular to their line of sight.
- Provide good light, make sure the pictures maintain the proper axis of polarization before the participants at 15 minutes of arc at a distance of 16 inches.
- Only do the circle test. Point to each item on the left hand side of the page going left to right and up to down. 
- Start with No.1. 

Say:

>"*This test assesses your stereoacuity. Do you see the butterfly? Can please trace it? Look at each of the four circles and tell me which one seems to come out closer to you-top, bottom, right, or left.*" 

Continue until participant gives up trying, or making two successive mistakes.
- Some participants may develop this perceptual response slowly. So let them study it for a while or let them change the viewing angle, if needed.

##### Report results

- Log the answer to each item on the [score sheet](vision-screening-score-sheet.html).
- Record the level of stereopsis into Qualtrics at the last one chosen correctly. 
