---
title: "Study parameters"
author: "Yiming Qian, Andrea Seisler, & Rick Gilmore"
date: "`r Sys.time()`"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

The following summarizes the display and experimental parameters for the two studies in order to clarify which ones we have chosen for our replication.

Abramov, I., Gordon, J., Feldman, O., & Chavarga, A. (2012). Sex & vision I: Spatio-temporal resolution. *Biology of Sex differences*, *3*(1), 20. bsd.biomedcentral.com. Retrieved from http://dx.doi.org/10.1186/2042-6410-3-20

Murray, S. O., Schallmo, M.-P., Kolodny, T., Millin, R., Kale, A., Thomas, P., Rammsayer, T. H., et al. (2018). Sex differences in visual motion processing. *Current Biology*, Retrieved from http://dx.doi.org/10.1016/j.cub.2018.06.014

## Murray et al.

- contrast levels (low = 3%, high = 98%) 
- Diameter = 0.84, 1.7 and 10° 
- Motion speed was 4 cycles/s (Hz)
- spatial frequency was 1.2 cycles/°. 
- Gratings were presented within a circular aperture, whose edges were blurred with a Gaussian envelope (SD = 0.21°)
- Trials began with a central fixation mark, a small shrinking circle (850 ms). 
- This was followed by a blank screen (150 ms)
- after which the grating stimuli appeared (variable duration controlled by a staircase procedure, range 6.7 – 333 ms)
- followed by another blank screen (150 ms), and finally a fixation mark (the response cue)

## Abramov et al. 2012

## Tabular comparison

| Parameter | Abramov | Murray |
|-----------|---------|--------|
| Stimulus  | grating | grating |
| Spatial frequency (cyc/$^{\circ}$) | 0.6, 1, 2, 5, 12, 24.4 | 1(UR[^1]), 1.2(UW[^2]) |
| Temporal frequency (cyc/s; Hz)     | 1, 4, 8, 15, 24 | 4(UW) |
| Speed (cyc/s)                      |                 | 4(UR), 4.8(UB[^3])  |     
| Contrast            | via staircase           | 0.3\%(UW), 42\%(UR), 95\%(UB), 98(UW)\%|
| Contrast modulation | sinusoidal counterphase | left/right motion |
| Temporal onset      | 0.5s ramp up; 1s steady at max contrast; 0.5s ramp down | trapezoidal rise, steady, decline |
| Mask/shape          | circular | gaussian, SD=0.21$^{\circ}$(UW), raised cosine(UR, UB) |
| Size ($^{\circ}$)   | 3.5      | 0.85(UW), 1.7(UW), 2(UR, UB), 4(UR, UB), 6(UB), 8(UR, UB), 10(UW) |
| Surround            | White 13$^{\circ}$ x 13$^{\circ}$ | |
| View distance       | 3600cm   | 66cm(UW), 146cm(UR) |
| Task                | Orientation discrimination: horizontal/vertical | Direction discrimination: left/right |
| Response period     | Unlimited | |
| Feedback            | Auditory (correct trials) | |
| Training trials     | No                        | |
| Staircase algorithm | QUEST                     | Psi(UW), QUEST(UR, UB) |
| Staircase trials    |                           | 30 + 10 catch trials, 44(UB) |
| Threshold parameters |                          | 80\%(UR), 82\%(UB) |
| $n$ staircases/condition |                      | 4(UW), 2 practice + 6(UR), 6(UB) |
| Threshold calculation |                         | median of 4(UW); drop high+low then mean of 4(UR), drop high+low then mean of 4(UB) |


## Replication parameters

### Criteria

1. Parameters that **maximize** sex differences.
2. Parameters that **minimize** sex differences.
3. Parameters that permit comparison between the two paradigms.

### Choices and justification

#### Abramov

1. Maximize differences
  - High spatial frequency (12, 24.4 cyc/deg)
  - Lower temporal frequencies (1, 4, 8 Hz)
3. Compare between paradigms
  - Contrast varies, so can't equate
  - Use 3.5 or 4 deg in diam
  - Use 4 Hz to equate with Murray
  - Can't equate spatial frequency with Murray and maximize sex difference
  - 1 replications per condition  

#### Murray

1. Maximize differences
  - High contrast (98\% vs. 3\%)
  - 4 deg in diam
3. Compare between paradigms
  - Used 1.2 cyc/deg, conflicts with maximizing sex differences in Abramov
  - 3.5 or 4 deg in diam
  - Can't equate contrast
  - Use 4 Hz as in Murray
  - Multiple replications per condition
  
#### Recommendations

**MUST**
- Abramov: 12 cyc/deg, 4 Hz, 3.5 deg diam, 4 reps
- Murray: 1.2 cyc/deg, 4 Hz, 3.5 deg diam, 4 reps, 98\%contrast

**POSSIBLE, IF TIME**
- Abramov: 1.2 cyc/deg (minimize sex differences)
- Murray: 3\% contrast (minimize sex difference)
  
- Decided **NOT** to have catch trials, but decide on criteria for dropping participants or runs based on threshold estimation.  

---

[^1]: University of Washington cohort
[^2]: University of Rochester cohort
[^3]: University of Bern cohort
