---
title: "Set-up Checklist"
author: "Yiming Qian, Andrea Seisler, & Rick Gilmore"
date: "`r Sys.time()`"
output:
  html_document:
    keep_md: true
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

## Before participant arrives

1. Check to see if there have been any cancellations.

### Vision Screening Preparation

Materials for vision screening are stored on the table next to Andrea's office.

- Make sure the black tape is on the floor 10ft from the HOVT Snellen Acuity Chart
- Place Stereo Acuity Test on table
- Place Color Vision Test on table (adult only)

### Monitor

- Turn on the **CRT monitor** in 503B. 
503B is the small testing room inside 503. 
The button for the monitor is in the back.

### Computer(s)

- In 503B switch on power of large surge protector on bottom left shelf.
- Turn on the computer
- Log-in
- Start Psychopy
- Double-check monitor settings within Windows
  - Contrast:
  - Brightness:
  - Screen width (in cm)
  - Screen resolution (choose monitor settings on PC)
- Check monitor within Psychopy

- Log-in to survey computer
- Load page with surveys: <https://pennstate.qualtrics.com/jfe/form/SV_8dhFCPvGSf0zSTz>

## After participant arrives

### Welcome participant

Say:

>*"Welcome. Are you XXX? This project about individual difference in motion perception. You will have ... The risk includes .Do you have any questions? 
You can withdraw anytime when you feel uncomfortable or .Do you want to go on?”*

- Store belongings in X.

- Talk with participant to complete the following 
  - Check the name
  - Consent Form, get verbal approval 

Say:

**IMPLIED/VERBAL CONSENT**

### Questionnaires

- Enter the ID: YYYY-MM-DD-HHMM based on appointment time
- Let the participants finish the items
-	A little break for the participants. If the participant wants to keep going, lead him to the test room

Say:

>"You have finished the first part of testing. Next you have  behavorial testing. Do you want to continue or have a little break?"

### Complete vision testing

- Complete Vision Screening (pattern acuity)
  - Adult - HOTV @ 10ft
- Complete Stereo Acuity Test
- Complete Color Vision Test
  
### Experimental Setup

- Guide participant to testing room.
- Have them sit in the chair.
- Adjust the monitor and participant position.
- The monitor should be located **60cm** from the bridge of the nose on the participant.
- The chair height should be set so the participant is looking directly at the **X** in the middle of the screen.
- Guide the participant to use the arrow keys for responses.

### Run Experiments

The order of the computer experiments will be randomized across participants using **X** procedure.

#### Murray et al.

```{r, child="murray-etal-task.Rmd"}
```

#### Abramov et al.

- Open the files "" located in folder.
- In PsychoPy, press the green button. 
- Enter the ID in the pop window and speak to the participant.

>“Okay. You can follow the instructions and do the tasks in the computer. I am outside this room, if you have questions,..."

## After session ends

- After the participant finishes all the tests, thank him/her.

>“Thank you for participating this experiment. Do you have any questions?“

### Give participant credit on SONA

- Assign credit in SONA.

### Clean-up

- Clean keyboard, mouse and table and begin [data export](sex-differences-data-export.md) (separate protocols).

### Data export

- Data must be copied to a USB flash drive from the testing PC.
- Data will be copied to Box.
- After data export is complete, turn off computer and monitor in 503B.
- Qualtrics data will be retrieved by...
