---
title: "Snellen Vision Screening Protocol"
author: "Yiming Qian, Andrea Seisler, & Rick Gilmore"
date: "`r Sys.time()`"
output:
  html_document:
    keep_md: true
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

<!-- # Vision Screening Instructions -->

<!-- #### Snellen Acuity (Child/Adult) -->

##### Procedure

- Have participant stand 10 feet away from the chart on the wall (black tape on the floor)
- Ask the participant to start with the top line and have the participant read the first symbols in every line in descending order

>"Could you read the first symbols in each line, beginning from the top?" 

- If they miss a letter, circle it on the score sheet.
- Move back up one line and ask the participant to identify all the optotypes on that line. If the participant identifies all symbols correctly, go to the next line with smaller optotypes and ask the participant to identify all optotypes on the line.

> "Could you read all the symbols in this line? And this line?" 

- Their visual acuity will be the one that matches the line on which 50% (3 of 5, 4 of 6) of the symbols are identified correctly.

##### Report results

- Log the answer to each item on the [score sheet](vision-screening-score-sheet.html).
- Log the acuity for the participant in terms of 10 ft (e.g. 10/10)
- Report the result into Qualtrics

