---
title: "Vision Screening Instructions"
author: "Yiming Qian, Andrea Seisler, & Rick Gilmore"
date: "`r Sys.time()`"
output:
  html_document:
    keep_md: true
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

<!-- # Vision Screening Instructions -->

##### Snellen Acuity (Child/Adult)
- Stand 10 feet away from the chart on the wall (black tape on the floor)
- Start with the top line and have the participant read the first symbols in every line in descending order
- If they miss a letter, circle it on the score sheet.
- Move back up one line and ask the participant to identify all the optotypes on that line. If the participants identifies all symbols correctly, go to the next line with smaller optotypes and ask the child to identify all optotypes on the line.
- Their visual acuity will be the one that matches the line on which 50% (3 of 5, 4 of 6) of the symbols are identified correctly.

Report result:
- Log the acuity for the participant in terms of 10 ft (e.g. 10/10)

##### Color Test (Child/Adult)
- The examination should be done indoors with bright, natural illumination of more than 300 lux.
- the plates should be held at a distance of 50 - 75 cm (20-30 inches)
- The first exam:
    - *Skip: Examiner shows the participant plate 1 or 2, tracing the red line. Recognized as "circle", "square", or some other design.
    - plate 3 and 4. The participants are required to say outloud "circle", "square", or some other design. If the shape is correctly recognized, mark as normal.If the shape is not correctly recognized, mark as abnormal.
- The second exam:
    - Skip: Examiner shows the participant plate 5. Recognized as a curve line. 
    - Plate 6: In tracing the winding line between the upper left mark x and lower right mmark x, the normal traces the red curve, but the abnormal usually trace the blue.
    - Plate 7: In tracing the winding line between the upper left mark x and lower right mmark x, the normal traces the upper green curve, but the abnormal usually trace the lower red curve.
    - Plate 8: In tracing the winding line between the upper left mark x, the normal can trace upper and lower curve and come back to the starting mark. In case of the abnormal, some can trace either 

Report result:
- Those who can not recognize any curve in plate 8 at all, or any lower curve are definitely abnormal
- They might be abnormal if they misjudge more than 3 plates among plates 3,4,6,7
- If they misjudge 1-2 plates among plates 3,4,6,7, it is better to re-examine him in details from plate 1-8. 

- The first exam:
    - Examiner shows the participant plate 1 or 2, tracing the red line. Recognized as "circle", "square", or some other design.
    - Then, plate 3 or 4. The participants are required to say outloud "circle", "square", or some other design. If the shape is correctly recognized, mark as normal.If the shape is not correctly recognized, mark as abnormal.
- The second exam:
    - Examiner shows the participant plate 5. Recognized as a curve line. 
    - Plate 6: In tracing the winding line between the upper left mark x and lower right mark x, the normal traces the red curve, but the abnormal usually trace the blue. If the participants recognize the blue curve, ask whether they see any other shape.
    - Plate 7: In tracing the winding line between the upper left mark x and lower right mmark x, the normal traces the upper green curve, but the abnormal usually trace the lower red curve. If the participants recognize the red curve, ask whether they see any other shape.
    - Plate 8: In tracing the winding line between the upper left mark x, the normal can trace upper and lower curve and come back to the starting mark. In case of the abnormal, some can trace either. 

##### Stereo Vision Test

- Have the participant put the stereo glasses on.
- provide good light, make sure the pictures maintain the proper axis of polarization before the participants at 15 minutes of arc at a distance of 16 inches.
- Only do circle test. Point to each item on the left hand side of the page going left to right and up to down. 
- Start with No.1. Say to the participant:" Look at each of the four circles and tell me which one seems to come out closer to you-top, bottom, right, or left." Continue until participant gives up trying, or making two successive mistakes.
- Some participants may develop this perceptual response slowly. So let them study it for a while, if needed.3

Report result:
- Log the answer to each item on the score sheet.
- Record the level of stereopsis at the last one chosen correctly. 


