---
title: "Sex differences project mtg notes"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2020-09-14

- Attending Yiming, Rick
- Topics
  - Survey of MOCO psychophysics study child participants
    - Have permission to contact from FiRST families
    - Can modify existing sex differences protocol for this new population
    - Questions:
      - Can these children do the object rotation task? ROG thinks yes, but let's see what other prior literature there is on the Shepard-Metzler task. Also ask SB.
      - ARS raised issue about the two different groups of coherence and how to evaluate. ROG says let's wait to see who we can recruit.
  - Evaluate sex differences in prior MOCO (or even MOFO) EEG participants
    - Let's ask for permission (via current sex diffs protocol) to contact
    - In parallel, look at the EEG data to see whether sex matters.
  - Analysis of existing sex diffs data (collected through March 2020)
  

## 2019-10-03

- Attending: Andrea, Yiming, Rick
- Topics
  - Revision of IRB protocol; Yiming will resubmit today
  - Rick will help with Murray et al. (now called temporal threshold or $T^2$) task.
  - Added terminology document to protocol.
  - Reviewed the consent and survey document.
  - Yiming will check Qualtrics URL and add to consent and survey document.
  - Yiming will create SONA protocol in expecation of IRB approval
  - ??? Add SONA link to internal protocol. Ideally use the study-specific URL if that works.
  - Andrea will forward monitor calibration email to Rick; Rick will ask for $ from Mel and Michele.

## 2019-09-26-11:08

- Attending: Andrea, Yiming, Rick
- Topics
  - Equipment
    - New PC here; set-up; connects to high res monitor; additional set-up (ARS) in-process
    - IT request submitted (ARS) for Psychopy install, internet, LA admin, computer admin, dual boot
    - ARS: Find monitor testing protocol - Current EEG/MRI [protocol](https://gilmore-lab.github.io/protocols/Calibrate-Monitor.md) and [code](https://gilmore-lab.github.io/gilmore-lab/photometer_proj)
    - ARS: Contact calibration vendor, price new calibration 
        - The cost to calibrate the ILT1700 is $235 and $265 for the SED033. 
        - Request RMA [here](https://www.intl-lighttech.com/service-support/rma-form)
  - IRB
    - Filed 2019-09-19 
  - Stimulus code (YM)
    - Abramov component
      - YM will demo next week
    - Murray et al component
  - Questionnaires
    - YM give URLs to ARS
    - ARS create page using R Markdown [Sex Differences Consent and Survey](https://gilmore-lab.github.io/sex-differences-in-motion-perception/consent-and-survey.html)
  - SONA project page (YM/ARS)
    - Create page before IRB
    - Confirm that corrected-to-normal (bring glasses or contacts) is required for inclusion
    - Publish SONA page after IRB approval
  - Internal/detailed protocol
    - ARS draft
      - Participant ID scheme
        - Test date & sequential number
      - Scheduling
      - Confirmation
      - Equipment set-up ()
      - Consent
      - Vision screening
        - Snellen acuity (how record data?)
      - Questionnaires
      - Decide on test order
      - Run visual test 1
      - Break
      - Run visual test 2
      - Debrief
      - Give credit
      - Post-processing
        - Transfer data from computer to Box
        - Download questionnaire data and transfer to Box
    - Post-processing QA/visualization
      - Explore use of Qualtrics R package
      - Subject-specific QA reports (R Markdown)
