---
title: "Gather and Clean Contrast Sensitivity (Abramov)"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  html_document:
    self_contained: no
params:
  path_2_data:  "~/Box\ Sync/Project_Sex_difference_on_Motion_Perception/data/contrast_sensitivity_task_data/"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```

## Purpose

This script imports, summarizes, and shows basic visualizations of an individual's session data.

## Import

```{r}
csv_files <- list.files(params$path_2_data, pattern = "\\.csv$", full.names = TRUE)

extract_subj_data <- function(fl) {
  s_data <- readr::read_csv(fl)
}

# Participant is participant ID YYYYMMDDHHMMSSnn
# Gender should be in c('m', 'f')
# loop_trial.intensity is the contrast level
# 
# loop_trial.thisN is in 0..29
# correctAns is left/right for correct orientation
# resp is 1, 0 for correct/incorrect
# resp.rt is RT in seconds
csv_files
```

```{r}
s1 <- readr::read_csv(csv_files[1])

s1_clean <- s1 %>%
  mutate(., correctAns = stringr::str_extract(correctAns, "left|down|right|up")) %>%
  mutate(., corr = if_else(resp == correctAns, 1, 0)) %>%
  rename(., contr = loop_trial.intensity,
         trial_n = loop_trial.thisN)

s1_subset <- s1_clean %>%
  dplyr::select(., Participant, Gender,
                trial_n,
                contr,
                correctAns,
                resp,
                corr,
                resp.rt) %>%
  dplyr::filter(., trial_n >= 0) %>%
  dplyr::mutate(run = rep(1:4, each=30))
s1_subset
```

## Visualize

```{r}
s1_subset %>% ggplot(.) +
  aes(x = trial_n, y = contr) +
  facet_grid(correctAns ~ run) +
  geom_smooth() +
  geom_point(aes(shape = factor(corr, labels = c("incorr", "corr"))))
```

### Cumulative performance across runs

```{r}
s1_subset <- s1_subset %>%
  dplyr::group_by(., run) %>%
  dplyr::arrange(., contr) %>%
  dplyr::mutate(., cum_sum = cumsum(corr),
                cum_p = cum_sum/n())

s1_subset %>% ggplot(.) +
  aes(x = contr, y = cum_p) +
  facet_grid(correctAns ~ run) +
  geom_point() +
  geom_smooth(se = FALSE)
```

```{r}
s1_subset %>%
  dplyr::group_by(., run, correctAns) %>%
  dplyr::summarise(p_corr = sum(corr)/n()) %>%
  ggplot(.) +
  aes(x = run, y = p_corr) +
  facet_grid(correctAns ~ .) +
  geom_col()
```

```{r}
s1_subset %>%
  ggplot(.) +
  aes(x = trial_n, y = resp.rt) +
  facet_grid(. ~ run) + 
  geom_point()
```


## Subject 2

```{r}
s2 <- readr::read_csv(csv_files[2])

s2_subset <- s2 %>%
  dplyr::select(., Participant, Gender,
                loop_trial.thisN,
                loop_trial.intensity,
                correctAns,
                resp,
                resp.rt) %>%
  dplyr::filter(., loop_trial.thisN >= 0) %>%
  dplyr::mutate(run = rep(1:4, each=30))
s2_subset
```

```{r}
s2_subset %>% ggplot(.) +
  aes(x = loop_trial.thisN, y = loop_trial.intensity) +
  facet_grid(. ~ run) +
  geom_point() +
  geom_smooth()
```

