---
title: "plot-helper"
output: html_document
---

## Setup

```{r}
if (!require("gridExtra")){
  install.packages("gridExtra")
}

library(gridExtra)
library(patchwork)

our_color_palette = "Dark2"
our_colors <- RColorBrewer::brewer.pal(n = 3, name = our_color_palette)
plot_point_size <- 0.75
```

```{r ggplot-themes}
# "The APA has determined specifications for the size of figures and the fonts used in them. Figures of one column must be between 2 and 3.25 inches wide (5 to 8.45 cm). Two-column figures must be between 4.25 and 6.875 inches wide (10.6 to 17.5 cm). The height of figures should not exceed the top and bottom margins. The text in a figure should be in a san serif font (such as Helvetica, Arial, or Futura). The font size must be between eight and fourteen point. Use circles and squares to distinguish curves on a line graph (at the same font size as the other labels). "
theme.custom <- theme_classic() +
  theme(
    plot.title = element_text(size = 13, face = "bold", hjust = 0.5),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    strip.text = element_text(size = 11),
    axis.text = element_text(size = 11),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    aspect.ratio = 1
  )
```

### Histograms

```{r}
sex_diff_boxplot <- function(df = sex_diff_df,
                             x_var = "Sex",
                             y_var = "log_contrast",
                             axis_label = "log(contrast)") {
  x_var_s <- sym(x_var)
  y_var_s <- sym(y_var)
  
  p <- ggplot(df) +
    aes(
      x = !!x_var_s,
      y = !!y_var_s,
      group = Sex,
      color = Sex
    ) +
    geom_boxplot(outlier.shape = NA, color = "black") +
    geom_jitter(size = plot_point_size,
                height = .1,
                width = .1,
                alpha = 1/2) +
    scale_color_brewer(palette = our_color_palette) +
    theme.custom +
    ylab(axis_label) +
    theme(legend.position = "none") +
    theme(axis.title.x = element_blank())
  p
}

sex_diff_boxplot(sex_diff_df)
```


```{r, hist_contrast}

p_hist_contrast <- sex_diff_boxplot(y_var = "log_contrast", axis_label = "log(contrast)")

p_hist_contrast
```

```{r, hist_motion}
p_hist_motion <- sex_diff_boxplot(y_var = "log_motion", axis_label = "log(motion)")

p_hist_motion
```
```{r, hist_mental_rot}
p_hist_mental_rot <- sex_diff_boxplot(y_var = "mental_rot", axis_label = "Mental rotation score")

p_hist_mental_rot
```
```{r, hist_interests}
p_hist_interests <- sex_diff_boxplot(y_var = 'Masculine_hobbies', axis_label = "Male-typed activities")

p_hist_interests
```

### Scatterplots

```{r}
sex_diff_scatter <-
  function(df,
           x_var,
           y_var,
           x_rev = FALSE,
           y_rev = FALSE,
           an_f = "",
           an_m = "",
           anx = NULL,
           any = NULL,
           x_lab = "X axis",
           y_lab = "Y axis",
           square_axis = TRUE) {
    require(tidyverse)
    
    x_var_s <- sym(x_var)
    y_var_s <- sym(y_var)
    
    p <- ggplot(df) +
      aes(
        x = !!x_var_s,
        y = !!y_var_s,
        group = Sex,
        fill = Sex,
        color = Sex
      ) +
      geom_jitter(size = plot_point_size) +
      stat_smooth(
        method = "lm",
        se = FALSE,
        na.rm = TRUE
      ) +
      xlab(x_lab) +
      ylab(y_lab) +
      theme.custom +
      annotate(
        "text",
        x = anx,
        y = any,
        size = 5,
        label = c(an_f, an_m),
        color = our_colors[1:2],
        hjust = 0 # left-justified
      )
      
    p <- p + scale_color_brewer(palette = our_color_palette)
    
    if (square_axis)
    {
      p + coord_fixed() + theme(asp.ratio = 1)
    }
    
    # if (stringr::str_detect(x_var, 'hobbies')) {
    #   p <- p + xlim(1, 5)
    # }
    # if (stringr::str_detect(y_var, 'hobbies')) {
    #   p <- p + ylim(1, 5)
    # }
    
    # Reverse scale for threshold measures?
    if (x_rev)
      p <- p + scale_x_reverse()
    if (y_rev)
      p <- p + scale_y_reverse()
    
    p
  }
```

Create matrices of correlation coefficients for subsequent plotting.

```{r}
corr_vars <- c('log_contrast', 'log_motion', 'mental_rot', 'Masculine_hobbies')
df_corr_F <- sex_diff_df_F %>%
  dplyr::select(., corr_vars)

corr_F <- Hmisc::rcorr(as.matrix(df_corr_F), type = c("pearson"))

df_corr_M <- sex_diff_df_M %>%
  dplyr::select(., corr_vars)

corr_M <- Hmisc::rcorr(as.matrix(df_corr_M), type = c("pearson"))

df_corr_all <- sex_diff_df %>%
  dplyr::select(., corr_vars)

corr_all <- Hmisc::rcorr(as.matrix(df_corr_all), type = c("pearson"))
```

Create a helper function to generate and plot correlation coefficients.

```{r sex-diff-corr-sum-function}
sex_diff_corr_summ <- function(x_var, y_var, print_table = TRUE, 
                               corr_all_df = corr_all,
                               corr_M_df = corr_M,
                               corr_F_df = corr_F,
                               show_combined = FALSE) {
  require(tidyverse) # for %>%
  
  corr_all_df <- tibble::tibble(
    cor_coef = corr_all_df$r[x_var, y_var],
    p_val = corr_all_df$P[x_var, y_var],
    n =  corr_all_df$n[x_var, y_var],
    pop = "Both"
  )
  
  males_df <- tibble::tibble(
    cor_coef = corr_M_df$r[x_var, y_var],
    p_val = corr_M_df$P[x_var, y_var],
    n =  corr_M_df$n[x_var, y_var],
    pop = "Males"
  )
  
  females_df <- tibble::tibble(
    cor_coef = corr_F_df$r[x_var, y_var],
    p_val = corr_F_df$P[x_var, y_var],
    n =  corr_F_df$n[x_var, y_var],
    pop = "Females"
  )
  
  if (show_combined) {
    df <- rbind(corr_all_df, males_df, females_df)
  } else {
    df <- rbind(males_df, females_df)
  }
  
  # Add stars for significance levels
  df <- df %>%
    mutate(., stars = if_else(p_val < .005, "***",
                              if_else(
                                p_val < .01, "**",
                                if_else(p_val < .05, "*", "")
                              )))
  
  if (print_table) {
    kableExtra::kable(df, format = 'html') %>%
      kableExtra::kable_styling()
  } else {
    df
  }
}
```

#### Mental rotation and contrast

```{r contrast-sens-mental-rot}
corr_df <- sex_diff_corr_summ(
  "log_contrast",
  "mental_rot",
  corr_all,
  corr_M_df = corr_M,
  corr_F_df = corr_F,
  print_table = FALSE
)

p_mental_rot_contrast <- sex_diff_scatter(
  sex_diff_df,
  "log_contrast",
  "mental_rot",
  x_rev = FALSE,
  y_rev = FALSE,
  paste0(
    "r = ",
    format(corr_df$cor_coef[2], digits = 2, nsmall = 2),
    corr_df$stars[2]
  ),
  paste0(
    "r = ",
    format(corr_df$cor_coef[1], digits = 2, nsmall = 2),
    corr_df$stars[1]
  ),
  c(-1.55),
  c(35, 38),
  "log(contrast threshold)",
  "Mental rotation score"
)

p_mental_rot_contrast
```
#### Mental rotation and motion

```{r motion-duration-mental-rot-annotate-outliers}
corr_df <- sex_diff_corr_summ("log_motion",
                              "mental_rot", print_table = FALSE)

p_motion <- sex_diff_scatter(
  sex_diff_df,
  "log_motion",
  "mental_rot",
  x_rev = FALSE,
  y_rev = FALSE,
  paste0(
    "r = ",
    format(corr_df$cor_coef[2], digits = 2, nsmall = 2),
    corr_df$stars[2]
  ),
  paste0(
    "r = ",
    format(corr_df$cor_coef[1], digits = 2, nsmall = 2),
    corr_df$stars[1]
  ),
  c(-1.55),
  c(35, 38),
  "log(motion threshold)",
  "Mental rotation score"
)

p_mental_rot_motion <- p_motion +
  ggplot2::annotate(
    geom = "point",
    x = sex_diff_df$log_motion[c(115, 118)],
    y = sex_diff_df$mental_rot[c(115, 118)],
    color = "black",
    size = 6,
    shape = 0
  )

p_mental_rot_motion
```
#### Male-typed interests and contrast

```{r contrast-sens-male-hobbies}
corr_df <- sex_diff_corr_summ(
  "log_contrast",
  "Masculine_hobbies",
  corr_all,
  corr_M_df = corr_M,
  corr_F_df = corr_F,
  print_table = FALSE
)

p_interests_contrast <- sex_diff_scatter(
  sex_diff_df,
  "log_contrast",
  "Masculine_hobbies",
  x_rev = FALSE,
  y_rev = FALSE,
  paste0("r = ",
         format(
           corr_df$cor_coef[2], digits = 2, nsmall = 2
         ),
         "*"),
  paste0(
    "r = ",
    format(corr_df$cor_coef[1], digits = 2, nsmall = 2),
    corr_df$stars[1]
  ),
  c(-1.5),
  c(4.35, 4.8),
  "log(contrast threshold)",
  "Interest in male-typed activities"
)
p_interests_contrast
```

#### Contrast and motion

```{r motion-duration-contrast-sens}
corr_df <- sex_diff_corr_summ("log_motion",
                              "log_contrast", print_table = FALSE)

p_vision <- sex_diff_scatter(
  sex_diff_df,
  "log_motion",
  "log_contrast",
  x_rev = FALSE,
  y_rev = FALSE,
  paste0(
    "r = ",
    format(corr_df$cor_coef[2], digits = 2, nsmall = 2),
    corr_df$stars[2]
  ),
  paste0(
    "r = ",
    format(corr_df$cor_coef[1], digits = 2, nsmall = 2),
    corr_df$stars[1]
  ),
  c(-1.4),
  c(-1.38, -1.3),
  "log(motion threshold)",
  "log(contrast threshold)"
)

p_vision_aug <- p_vision +
  ggplot2::annotate(
    geom = "point",
    x = sex_diff_df$log_motion[c(115, 118)],
    y = sex_diff_df$log_contrast[c(115, 118)],
    color = "black",
    size = 8,
    shape = 0
  )

p_vision_aug
```
### Export

```{r}
p_boxplots <- p_hist_contrast + p_hist_motion + p_hist_mental_rot + p_hist_interests
p_boxplots_annotated <- p_boxplots + plot_annotation(tag_levels = "A")
p_boxplots_annotated

ggsave(
  plot = p_boxplots_annotated,
  filename = "paper_figs/fig-01-boxplots.jpg",
  units = "in",
  width = 6.875,
  dpi = 600
)
```

```{r}
# Mental rotation and vision measures
p_mental_rot_scatters <- p_mental_rot_contrast | p_mental_rot_motion
p_mental_rot_scatters_annotated <- p_mental_rot_scatters + plot_annotation(tag_levels = "A")
p_mental_rot_scatters_annotated

ggsave(
  plot = p_mental_rot_scatters_annotated,
  filename = "paper_figs/fig-02-mental-rot-vision.jpg",
  units = "in",
  width = 6.875,
  dpi = 600
)
```

```{r}
# Mental rotation and vision measures
p = grid.arrange(ncol = 2, nrow = 1, p_mental_rot_contrast, p_mental_rot_motion)
ggsave(
  plot = p,
  filename = "paper_figs/fig-02-mental-rot-vision-alt.jpg",
  units = "in",
  width = 6.875,
  dpi = 600
)

# Contrast thresholds and motion thresholds
ggsave(
  plot = p_vision_aug,
  filename = "paper_figs/fig-03-contrast-motion.jpg",
  units = "in",
  width = 3.4375,
  dpi = 600
)

ggsave(
  plot = p_interests_contrast,
  filename = "paper_figs/fig-S01-mental-rot-interests.jpg",
  units = "in",
  width = 3.4375,
  dpi = 600  
)
```