---
title: "Individual session QA"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: html_document
params:
  csv_path: "csv/"
  data_fn: "2019-10-29-140253_temp_thresh.csv"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Purpose

This script describes the process for doing quality assurance (QA) review on each session.

## QA criteria

1. There are two datafiles for each participant:
  - One for the Abramov et al contrast sensitivity task `~/Box\ Sync/Project_Sex_difference_on_Motion_Perception/data/contrast_sensitivity_task_data/`
  - One for the Murray et al temporal threshold task `~/Box\ Sync/Project_Sex_difference_on_Motion_Perception/data/motion_sensitivity_task_data/`
2. There is survey data for each participant in `~/Box\ Sync/Project_Sex_difference_on_Motion_Perception/data/qualtrics_data/`
3. There are four runs for each of two computer-based tasks, each run consisting of $n=30$ trials.
4. The computer-based tasks have the participant gender.

## QA steps

1. Move `*.csv`, `*.pydat`, and `*.log` files to separate subdirectories.
2. List `*.csv` contrast sensitivity files
3. List `*.csv` temporal threshold files
4. Do lists align?
  - If not, do what?
5. Determine if QA has already been run.
  - How?
    - Determine if `*.html` file exists for this subject
6. If QA not-run, run QA.
  - Create `*.html` file from `*.Rmd` template.

